#!/bin/bash
# setup-claudehp.sh - Standalone CLIProxyAPI configuration

set -e  # Fail fast

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== configured claude-hopee (Proxy) ===${NC}"

# Detect shell
SHELL_RC="${HOME}/.zshrc"
if [[ "$SHELL" == */bash ]]; then
    SHELL_RC="${HOME}/.bashrc"
    echo "Detected Bash shell. Config file: $SHELL_RC"
elif [[ "$SHELL" == */zsh ]]; then
    SHELL_RC="${HOME}/.zshrc"
    echo "Detected Zsh shell. Config file: $SHELL_RC"
else
    # Default to .zshrc if unknown, or maybe warns
    echo "Warning: Unknown or unsupported shell ($SHELL). Defaulting to ~/.zshrc"
    SHELL_RC="${HOME}/.zshrc"
fi

# Ensure ~/.claude directory exists
mkdir -p "${HOME}/.claude"

# 1. Key Input & Validation
CLIPROXY_KEY=""

# Check if key exists in shell config
if grep -q "CLIPROXY_API_KEY" "$SHELL_RC" 2>/dev/null; then
    # Try to extract existing key
    CURRENT_KEY=$(grep "CLIPROXY_API_KEY" "$SHELL_RC" | head -n 1 | cut -d'=' -f2 | tr -d '"' | tr -d "'")
    if [ ! -z "$CURRENT_KEY" ]; then
        echo -e "Found existing key: your key"
        read -p "Overwrite? (y/N): " confirm
        if [[ "$confirm" =~ ^[Yy]$ ]]; then
            read -p "Enter Proxy key: " CLIPROXY_KEY
        else
            CLIPROXY_KEY="$CURRENT_KEY"
            echo "Using existing key."
        fi
    else
        read -p "Enter Proxy key: " CLIPROXY_KEY
    fi
else
    read -p "Enter Proxy key: " CLIPROXY_KEY
fi

# Validate non-empty
if [ -z "$CLIPROXY_KEY" ]; then
    echo -e "${RED}Error: API key required${NC}"
    exit 1
fi

# 2. Generate Wrapper Script
WRAPPER_PATH="${HOME}/.claude/claude-hopee.sh"
echo "Generating wrapper at $WRAPPER_PATH..."

cat > "$WRAPPER_PATH" << 'EOF'
#!/bin/bash
# claude-hopee - Claude Code via CLIProxyAPI
# Auto-generated by setup-claudehp.sh

# Check for API key
if [ -z "$CLIPROXY_API_KEY" ]; then
    echo "Error: CLIPROXY_API_KEY not set"
    echo "Run setup-claudehp.sh again"
    exit 1
fi

# Proxy Configuration
export ANTHROPIC_BASE_URL=http://192.168.3.114:8317
export ANTHROPIC_AUTH_TOKEN="$CLIPROXY_API_KEY"

# Model Defaults
export ANTHROPIC_DEFAULT_HAIKU_MODEL=claude-haiku-4-5-20251001
export ANTHROPIC_DEFAULT_SONNET_MODEL=claude-sonnet-4-5-20250929
export ANTHROPIC_DEFAULT_OPUS_MODEL=claude-opus-4-5-20251101

# Execute claude with all arguments using exec to replace the process
exec claude "$@"
EOF

chmod +x "$WRAPPER_PATH"

# 3. Update Shell Config
echo "Updating $SHELL_RC..."

# Backup first
TIMESTAMP=$(date +%s)
cp "$SHELL_RC" "${SHELL_RC}.backup.${TIMESTAMP}"
echo "Backup created at ${SHELL_RC}.backup.${TIMESTAMP}"

# Clean up old entries
# Use sed -i.bak for macOS compatibility, then remove the .bak file
sed -i.tmp '/CLIPROXY_API_KEY/d' "$SHELL_RC"
sed -i.tmp '/alias claudeHP/d' "$SHELL_RC"
sed -i.tmp '/alias claude-hopee/d' "$SHELL_RC"
rm -f "${SHELL_RC}.tmp"

# Add new entries
cat >> "$SHELL_RC" << EOF

# claude-hopee - Claude Code Proxy Setup
export CLIPROXY_API_KEY="$CLIPROXY_KEY"
alias claude-hopee='$WRAPPER_PATH'
alias claude-hopee-skip='$WRAPPER_PATH --dangerously-skip-permissions'
EOF

# 4. Verification
echo -e "${GREEN}✅ Setup complete!${NC}"
echo ""
echo "Configuration:"
echo "  - API Key: your key"
echo "  - Wrapper: $WRAPPER_PATH"
echo "  - Alias: claude-hopee"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "1. Reload your shell: source $SHELL_RC"
echo "2. Test it: claude-hopee \"hello\""
